# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: # WORKFLOW
  build: 

    runs-on: ubuntu-latest # SERVER RUNNER

    steps:
    - uses: actions/checkout@v4  # SEND THE LAST COMMIT TO THE RUNNER

    - name: Set up JDK 17 
      uses: actions/setup-java@v4 # INSTALL THE ENVIROMENT ON THE RUNNER
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Make gradlew executable # PERMISSIONS
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper # BUILDS AND DO TESTS
      run: |
        ./gradlew build
        echo "Done"
  
  docker:
    runs-on: ubuntu-latest

    steps:

    - name: Get PWD
      run: |
        echo "PWD:"
        pwd



    - name: Build and push
      uses: mr-smithers-excellent/docker-build-push@v6
      with: 
        image: macielsismoes04/test
        dockerfile: ./Dockerfile  
        registry: docker.io # DEFAULT SERVICE
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
