# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build: # WORKFLOW

    runs-on: ubuntu-latest # SERVER RUNNER

    steps:
    - uses: actions/checkout@v4  # SEND THE LAST COMMIT TO THE RUNNER

    - name: Set up JDK 17 
      uses: actions/setup-java@v4 # INSTALL THE ENVIROMENT ON THE RUNNER
      with:
        java-version: '17' 
        destribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: |
        ./gradlew build # IT'S HERE WHERE COMMIT WILL BE TESTED
        echo "Done"
